//! 虚拟项目目录与结构清单：让 Claude Code 等 coding agent 知道并能访问
//! 多仓库项目的全部成员仓库。
//!
//! 两个落点：
//! - 容器（multi != null 且非派生行）没有聚合目录，在 <falcon 根>/projects/<projectId>/
//!   生成一个虚拟目录当会话 cwd：AGENTS.md（成员绝对路径清单）+ CLAUDE.md（@import）
//!   + .claude/settings.json（Claude Code 的越 cwd 目录授权）。
//! - 批量派生的集中目录本身已经聚合了全部 worktree，只补 AGENTS.md + CLAUDE.md。
//!
//! 刻意不用软链聚合：实测 Claude Code 的 Glob 与 ripgrep 默认都不跟随软链目录，
//! 从聚合根递归搜索一无所获；带沙箱的 agent 还可能按 realpath 拒绝出逃。
//! 清单 + 真实路径对所有 agent 都是渐进增强（不认 settings.json 的最多退化成逐次授权）。
//!
//! 目录名用 projectId 不用 nameSlug：重名不撞、改名零孤儿，路径 = f(root, id)
//! 确定性可算，不用加 DB 列。内容全部模板确定性渲染——覆盖写天然幂等，
//! 守护删除（remove.ts）才能按字面比对"这是不是我们写的文件"。
//!
//! 与 paste.ts 同一分层：纯函数（路径/渲染/脚本构造）+ 本地 node:fs 例外。
//! SSH 侧不走 SFTP（理由同 fs.ts）；Windows 远端内容走 stdin base64 +
//! WriteAllBytes——Set-Content 默认按 ANSI 代码页写（中文机器上变 GBK），
//! `-Encoding UTF8` 又带 BOM（settings.json 的 JSON 解析会被它弄坏），
//! 内容内联进 -EncodedCommand 还可能顶穿 cmd.exe 的 8191 字符上限，全都不能用。
//!
//! 移植自 `packages/server/src/virtualdir.ts`。渲染出的三个文件已经落在宿主机上，
//! 守护删除按字面比对它们，所以全文必须与 TS 逐字节一致（测试里有整份比对）。
//!
//! 留到 S5 的函数（要读写本机文件）：`writeLocalManifest`（本地直接覆盖写清单）、
//! `removeLocalVirtualDir`（本地清理虚拟目录，ENOENT 视为 gone、其他失败落 left）。

use base64::Engine as _;

use crate::git::path::join_path;
use crate::zellij::host::{HostKind, encode_powershell, quote_posix, quote_powershell};

/// 生成物标记，放 AGENTS.md 首行注释里。守护删除按"首行含此标记"判断文件
/// 还是不是我们写的——刻意用 ASCII：跨编码可 grep，远端 head/grep 不吃编码亏。
pub const FALCON_GENERATED_MARK: &str = "generated by falcon";

/// CLAUDE.md 的确定性全文：单行 @import 指向 AGENTS.md。
/// 不复制全文——Claude Code 会同时认两个文件，复制会加载出双份内容；
/// 守护删除按"全文 trim 后精确等于 @AGENTS.md"比对，改一个字都视为用户文件。
pub const CLAUDE_MD_BODY: &str = "@AGENTS.md\n";

/// 清单文件：rel 用分段数组（写入/删除两侧共用一处真相，不手拼分隔符）。
///
/// TS 里 rel 是 `string[]`；这里收紧成 `&'static`：写入命令里 rel 段**不加引号**
/// （见 [`posix_write_manifest_command`]），只有我们自己的固定 ASCII 文件名才配进来，
/// 类型上就挡住运行时拼出来的段。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManifestFile {
    pub rel: &'static [&'static str],
    pub content: String,
}

/// 集中目录的一个成员：TS 的 `{ base: string; repoDir: string }`
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CentralMember {
    /// 成员 worktree 在集中目录里的目录名（仓库根的 basename）
    pub base: String,
    /// 源仓库根
    pub repo_dir: String,
}

/// Windows 远端的一条写入：命令 + 喂给它 stdin 的 base64（配 `SshLink.execWithInput`）
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WindowsManifestWrite {
    pub cmd: String,
    pub stdin_base64: String,
}

/// 容器虚拟目录的固定文件清单——删除侧只认这三个名字，多一个都不碰
const VIRTUAL_DIR_FILES: [&[&str]; 3] = [&["AGENTS.md"], &["CLAUDE.md"], &[".claude", "settings.json"]];

/// 虚拟目录：<falcon 根>/projects/<projectId>。root = 本地 dataDir 或远端 ~/.falcon
pub fn virtual_project_dir(kind: HostKind, root: &str, project_id: &str) -> String {
    join_path(kind, &[root, "projects", project_id])
}

// ---------------- 渲染 ----------------

/// 容器版 AGENTS.md。措辞是给 agent 看的操作指引，三条告诫对应实测到的坑：
/// 递归搜索不跟软链同理也搜不到 cwd 外——必须逐成员为根；成员是独立仓库。
pub fn render_container_agents_md<S: AsRef<str>>(project_name: &str, member_dirs: &[S]) -> String {
    let members = member_dirs.iter().map(|d| format!("- {}", d.as_ref())).collect::<Vec<_>>().join("\n");
    // 模板顶格写：字符串字面量里的换行与缩进原样进文件（第二行注释的 5 个空格是有意的）
    format!(
        "<!-- {FALCON_GENERATED_MARK} -->
<!-- 本文件与同目录的 CLAUDE.md、.claude/settings.json 由 falcon 自动生成并维护，
     成员变更或重开会话时会被整体覆盖，请勿手工编辑。 -->

# {project_name}（多仓库项目）

这是 falcon 为多仓库项目生成的虚拟项目目录：**当前目录下没有代码**，
全部代码都在下面列出的成员仓库里。在本项目中工作时请注意：

- 递归搜索（grep / glob / 代码索引）必须以每个成员目录为根分别进行，
  以当前目录为根搜索将一无所获。
- 读写文件一律使用成员目录下的绝对路径。
- 各成员是相互独立的 git 仓库，提交、分支操作要逐个成员进行，
  不要假设它们共享同一个仓库。

## 成员仓库

{members}
"
    )
}

/// 集中目录版：成员都在 cwd 内，用相对路径；不需要"cwd 下没有代码"的告诫
pub fn render_central_agents_md(project_name: &str, branch: &str, members: &[CentralMember]) -> String {
    let list = members
        .iter()
        .map(|m| format!("- ./{}/（源仓库 {}）", m.base, m.repo_dir))
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        "<!-- {FALCON_GENERATED_MARK} -->
<!-- 本文件由 falcon 在批量派生时生成，删除该派生项目时会被一并清理。 -->

# {project_name}（多仓库批量派生，分支 {branch}）

当前目录是 falcon 批量派生出的集中目录，下列子目录各是一个成员仓库的
git worktree（统一检出分支 {branch}）。各成员是相互独立的仓库，
提交、分支操作要逐个成员进行。

## 成员

{list}
"
    )
}

/// Claude Code 的越 cwd 目录授权。JSON.stringify 自带反斜杠转义，无 BOM、带尾换行。
///
/// 等价于 TS 的 `JSON.stringify({ permissions: { additionalDirectories } }, null, 2) + "\n"`。
/// 外层结构手写而不是交给 serde_json 的 Map：workspace 里 GPUI 会经 feature 合并打开
/// preserve_order，Map 的遍历顺序随构建变，而这份文件要逐字节稳定。字符串字面量的
/// 转义交给 serde_json——它与 JSON.stringify 的规则相同（`"` `\` 与 \b\f\n\r\t 用短形式，
/// 其余控制字符 `\u00xx` 小写，非 ASCII 原样）。
pub fn render_claude_settings<S: AsRef<str>>(member_dirs: &[S]) -> String {
    let dirs = if member_dirs.is_empty() {
        // JSON.stringify 的缩进模式下空数组也写成 []
        "[]".to_string()
    } else {
        let items = member_dirs
            .iter()
            .map(|d| format!("      {}", json_string(d.as_ref())))
            .collect::<Vec<_>>()
            .join(",\n");
        format!("[\n{items}\n    ]")
    };
    format!("{{\n  \"permissions\": {{\n    \"additionalDirectories\": {dirs}\n  }}\n}}\n")
}

fn json_string(s: &str) -> String {
    serde_json::to_string(s).expect("字符串序列化不会失败")
}

/// 容器虚拟目录的三个文件
pub fn container_manifest_files<S: AsRef<str>>(project_name: &str, member_dirs: &[S]) -> Vec<ManifestFile> {
    vec![
        ManifestFile { rel: VIRTUAL_DIR_FILES[0], content: render_container_agents_md(project_name, member_dirs) },
        ManifestFile { rel: VIRTUAL_DIR_FILES[1], content: CLAUDE_MD_BODY.to_string() },
        ManifestFile { rel: VIRTUAL_DIR_FILES[2], content: render_claude_settings(member_dirs) },
    ]
}

/// 集中目录的两个文件——成员都在 cwd 内，settings.json 没有存在的理由
pub fn central_manifest_files(project_name: &str, branch: &str, members: &[CentralMember]) -> Vec<ManifestFile> {
    vec![
        ManifestFile { rel: VIRTUAL_DIR_FILES[0], content: render_central_agents_md(project_name, branch, members) },
        ManifestFile { rel: VIRTUAL_DIR_FILES[1], content: CLAUDE_MD_BODY.to_string() },
    ]
}

// ---------------- 写入 ----------------

/// POSIX：一条命令建目录 + 逐文件 printf 覆盖写（ensureDirsScript 同款）。
/// 内容经 quotePosix 内联，单引号里的换行由 sh 原样保留；rel 段是我们自己的
/// 固定 ASCII 文件名，不需要引号。退出码 = 链上第一个失败者，调用方查 res.code。
pub fn posix_write_manifest_command(dir: &str, files: &[ManifestFile]) -> String {
    // TS 是 `[...new Set(...)]`：去重且保留首次出现的顺序
    let mut subdirs: Vec<String> = Vec::new();
    for f in files.iter().filter(|f| f.rel.len() > 1) {
        let sub = f.rel[..f.rel.len() - 1].join("/");
        if !subdirs.contains(&sub) {
            subdirs.push(sub);
        }
    }
    let mk_targets = std::iter::once("\"$d\"".to_string())
        .chain(subdirs.iter().map(|s| format!("\"$d\"/{s}")))
        .collect::<Vec<_>>()
        .join(" ");
    let writes = files
        .iter()
        .map(|f| format!("printf %s {} > \"$d\"/{}", quote_posix(&f.content), f.rel.join("/")))
        .collect::<Vec<_>>();
    format!("d={}; mkdir -p {mk_targets} && {}", quote_posix(dir), writes.join(" && "))
}

/// Windows 远端：逐文件一条 -EncodedCommand，配 SshLink.execWithInput 喂 base64。
/// 编码取舍见文件头注释。New-Item -Force 对已存在目录是幂等的（mkdirPS 同款，
/// 创建路径可以用 -Path，通配陷阱只在删除侧——见 install.ts 的 cleanup 注释）。
pub fn windows_write_manifest_commands(dir: &str, files: &[ManifestFile]) -> Vec<WindowsManifestWrite> {
    files
        .iter()
        .map(|f| {
            let target = join_path(HostKind::Windows, &[&[dir][..], f.rel].concat());
            let parent = if f.rel.len() > 1 {
                join_path(HostKind::Windows, &[&[dir][..], &f.rel[..f.rel.len() - 1]].concat())
            } else {
                dir.to_string()
            };
            let script = [
                format!("New-Item -ItemType Directory -Force -Path {} | Out-Null", quote_powershell(&parent)),
                "$b = [Convert]::FromBase64String([Console]::In.ReadToEnd())".to_string(),
                format!("[IO.File]::WriteAllBytes({}, $b)", quote_powershell(&target)),
            ]
            .join("; ");
            WindowsManifestWrite {
                cmd: encode_powershell(&script),
                stdin_base64: base64::engine::general_purpose::STANDARD.encode(f.content.as_bytes()),
            }
        })
        .collect()
}

// ---------------- 容器虚拟目录清理 ----------------
// 虚拟目录住在 falcon 根下，属 falcon 自有目录，参照 paste.ts 自行清理，
// 不进 remove.ts（那里管的是用户可见路径）。但删除动作同样克制：只删固定
// 文件名 + 非递归 rmdir——虚拟目录是会话 cwd，agent/用户可能在里面落了
// 别的文件，非空就整目录保留，stdout 报 left 让上层给 warning。

/// stdout 协议：gone = 目录已不在；left = 目录还在（内有其他文件）
pub fn posix_remove_virtual_dir_command(dir: &str) -> String {
    let files = VIRTUAL_DIR_FILES.iter().map(|rel| format!("\"$d\"/{}", rel.join("/"))).collect::<Vec<_>>().join(" ");
    format!(
        "d={}; rm -f -- {files}; \
         rmdir -- \"$d\"/.claude 2>/dev/null; \
         if [ ! -e \"$d\" ]; then printf gone; \
         elif rmdir -- \"$d\" 2>/dev/null; then printf gone; else printf left; fi",
        quote_posix(dir)
    )
}

/// Windows：[IO.File]::Delete / [IO.Directory]::Delete($p, $false) 吃字面量且
/// 非递归——不用 Remove-Item（-Path 的通配陷阱见 install.ts 的 cleanup 注释）。
/// File.Delete 对不存在的文件不抛，但父目录不存在时抛 DirectoryNotFound，
/// 所以每条都包 try/catch：删不掉的后果只是 rmdir 失败 → left，方向安全。
pub fn windows_remove_virtual_dir_command(dir: &str) -> String {
    let mut script = vec![
        format!("$d = {}", quote_powershell(dir)),
        "if (-not (Test-Path -LiteralPath $d)) { 'gone'; exit 0 }".to_string(),
    ];
    script.extend(VIRTUAL_DIR_FILES.iter().map(|rel| {
        format!("try {{ [IO.File]::Delete((Join-Path $d {})) }} catch {{}}", quote_powershell(&rel.join("\\")))
    }));
    script.push("try { [IO.Directory]::Delete((Join-Path $d '.claude'), $false) } catch {}".to_string());
    script.push("try { [IO.Directory]::Delete($d, $false); 'gone' } catch { 'left' }".to_string());
    encode_powershell(&script.join("; "))
}

pub fn remove_virtual_dir_command(kind: HostKind, dir: &str) -> String {
    if kind == HostKind::Windows {
        windows_remove_virtual_dir_command(dir)
    } else {
        posix_remove_virtual_dir_command(dir)
    }
}

// ---------------- 集中目录清单的守护删除脚本 ----------------
// 只构造脚本；执行住在 git/remove.ts（全仓库唯一删用户可见路径的地方）。
// 守护条件与生成物一一对应：AGENTS.md 首行含标记、CLAUDE.md 全文 trim 后
// 精确等于 @AGENTS.md——用户改写过的内容视为用户文件，宁可不删（后续的
// rmdir 会因非空失败，既有 warning 带路径，方向安全）。

pub fn posix_central_manifest_sweep_command(central: &str) -> String {
    format!(
        "d={}; \
         if [ -f \"$d\"/AGENTS.md ] && head -n 1 \"$d\"/AGENTS.md | grep -qF {}; \
         then rm -f -- \"$d\"/AGENTS.md; fi; \
         if [ -f \"$d\"/CLAUDE.md ] && [ \"$(cat \"$d\"/CLAUDE.md)\" = {} ]; \
         then rm -f -- \"$d\"/CLAUDE.md; fi",
        quote_posix(central),
        quote_posix(FALCON_GENERATED_MARK),
        quote_posix(CLAUDE_MD_BODY.trim())
    )
}

pub fn windows_central_manifest_sweep_command(central: &str) -> String {
    let script = [
        format!("$d = {}", quote_powershell(central)),
        "$a = Join-Path $d 'AGENTS.md'".to_string(),
        format!(
            "if ((Test-Path -LiteralPath $a) -and \
             ((Get-Content -LiteralPath $a -First 1) -like {})) \
             {{ [IO.File]::Delete($a) }}",
            quote_powershell(&format!("*{FALCON_GENERATED_MARK}*"))
        ),
        "$c = Join-Path $d 'CLAUDE.md'".to_string(),
        format!(
            "if ((Test-Path -LiteralPath $c) -and \
             ((Get-Content -LiteralPath $c -Raw).Trim() -eq {})) \
             {{ [IO.File]::Delete($c) }}",
            quote_powershell(CLAUDE_MD_BODY.trim())
        ),
    ]
    .join("; ");
    encode_powershell(&script)
}

pub fn central_manifest_sweep_command(kind: HostKind, central: &str) -> String {
    if kind == HostKind::Windows {
        windows_central_manifest_sweep_command(central)
    } else {
        posix_central_manifest_sweep_command(central)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::zellij::host::tests::decode;
    use HostKind::{Posix, Windows};
    use regex::Regex;

    fn assert_match(hay: &str, re: &str) {
        assert!(Regex::new(re).unwrap().is_match(hay), "{hay:?} 不匹配 /{re}/");
    }

    fn central(base: &str, repo_dir: &str) -> CentralMember {
        CentralMember { base: base.into(), repo_dir: repo_dir.into() }
    }

    /// TS：describe("virtualProjectDir")
    mod virtual_project_dir {
        use super::*;

        /// it("lives under <falcon root>/projects/<id> on either platform")
        #[test]
        fn lives_under_falcon_root_projects_id() {
            assert_eq!(virtual_project_dir(Posix, "/home/u/.falcon", "p-1"), "/home/u/.falcon/projects/p-1");
            assert_eq!(
                virtual_project_dir(Windows, "C:\\Users\\u\\.falcon", "p-1"),
                "C:\\Users\\u\\.falcon\\projects\\p-1"
            );
        }

        /// it("does not double separators when the root has a trailing one")
        #[test]
        fn does_not_double_separators() {
            assert_eq!(virtual_project_dir(Posix, "/data/", "id"), "/data/projects/id");
        }
    }

    /// TS：describe("renderContainerAgentsMd")
    mod render_container_agents_md {
        use super::*;

        const MEMBERS: [&str; 4] =
            ["/Users/fay/code with space/srv", "/home/o'brien/web", "/Users/fay/仓库/中文", "D:\\code\\repo"];

        fn md() -> String {
            render_container_agents_md("我的项目", &MEMBERS)
        }

        /// it("starts with the generated mark so the guarded sweep can recognize it")
        #[test]
        fn starts_with_the_generated_mark() {
            assert!(md().split('\n').next().unwrap().contains(FALCON_GENERATED_MARK));
        }

        /// it("lists every member path verbatim and names the project")
        #[test]
        fn lists_every_member_and_names_the_project() {
            let md = md();
            for m in MEMBERS {
                assert!(md.contains(&format!("- {m}")));
            }
            assert!(md.contains("# 我的项目"));
        }

        /// it("tells agents there is no code in cwd and to search per member root")
        #[test]
        fn tells_agents_no_code_in_cwd() {
            let md = md();
            assert!(md.contains("当前目录下没有代码"));
            assert!(md.contains("以每个成员目录为根"));
        }

        /// Rust 侧补充：全文与 TS 逐字节一致（tsx 跑 virtualdir.ts 取得）
        #[test]
        fn full_text_matches_ts() {
            assert_eq!(
                render_container_agents_md("p", &["/a", "D:\\b"]),
                "<!-- generated by falcon -->\n\
                 <!-- 本文件与同目录的 CLAUDE.md、.claude/settings.json 由 falcon 自动生成并维护，\n     \
                 成员变更或重开会话时会被整体覆盖，请勿手工编辑。 -->\n\
                 \n\
                 # p（多仓库项目）\n\
                 \n\
                 这是 falcon 为多仓库项目生成的虚拟项目目录：**当前目录下没有代码**，\n\
                 全部代码都在下面列出的成员仓库里。在本项目中工作时请注意：\n\
                 \n\
                 - 递归搜索（grep / glob / 代码索引）必须以每个成员目录为根分别进行，\n  \
                 以当前目录为根搜索将一无所获。\n\
                 - 读写文件一律使用成员目录下的绝对路径。\n\
                 - 各成员是相互独立的 git 仓库，提交、分支操作要逐个成员进行，\n  \
                 不要假设它们共享同一个仓库。\n\
                 \n\
                 ## 成员仓库\n\
                 \n\
                 - /a\n\
                 - D:\\b\n"
            );
        }
    }

    /// TS：describe("renderCentralAgentsMd")
    mod render_central_agents_md {
        use super::*;

        fn md() -> String {
            render_central_agents_md(
                "派生-feat",
                "feat/x",
                &[central("srv", "/Users/fay/code/srv"), central("web", "/Users/fay/code/web")],
            )
        }

        /// it("lists members as relative subdirs with their source repo roots")
        #[test]
        fn lists_members_as_relative_subdirs() {
            let md = md();
            assert!(md.contains("- ./srv/（源仓库 /Users/fay/code/srv）"));
            assert!(md.contains("- ./web/（源仓库 /Users/fay/code/web）"));
        }

        /// it("names the branch and carries the generated mark")
        #[test]
        fn names_the_branch_and_carries_the_mark() {
            let md = md();
            assert!(md.contains("feat/x"));
            assert!(md.split('\n').next().unwrap().contains(FALCON_GENERATED_MARK));
        }

        /// Rust 侧补充：全文与 TS 逐字节一致（tsx 跑 virtualdir.ts 取得）
        #[test]
        fn full_text_matches_ts() {
            assert_eq!(
                render_central_agents_md("p", "b", &[central("x", "/r/x")]),
                "<!-- generated by falcon -->\n\
                 <!-- 本文件由 falcon 在批量派生时生成，删除该派生项目时会被一并清理。 -->\n\
                 \n\
                 # p（多仓库批量派生，分支 b）\n\
                 \n\
                 当前目录是 falcon 批量派生出的集中目录，下列子目录各是一个成员仓库的\n\
                 git worktree（统一检出分支 b）。各成员是相互独立的仓库，\n\
                 提交、分支操作要逐个成员进行。\n\
                 \n\
                 ## 成员\n\
                 \n\
                 - ./x/（源仓库 /r/x）\n"
            );
        }
    }

    /// TS：describe("CLAUDE_MD_BODY")
    mod claude_md_body {
        use super::*;

        /// it("is exactly the one-line import — the guarded sweep compares it literally")
        #[test]
        fn is_exactly_the_one_line_import() {
            assert_eq!(CLAUDE_MD_BODY, "@AGENTS.md\n");
        }
    }

    /// TS：describe("renderClaudeSettings")
    mod render_claude_settings {
        use super::*;

        /// it("round-trips through JSON.parse, backslashes intact")
        #[test]
        fn round_trips_through_json_parse() {
            let dirs = ["/a/b", "D:\\code\\仓库", "/home/o'brien/x"];
            let text = render_claude_settings(&dirs);
            let parsed: serde_json::Value = serde_json::from_str(&text).unwrap();
            assert_eq!(parsed, serde_json::json!({ "permissions": { "additionalDirectories": dirs } }));
        }

        /// it("has no BOM and ends with a newline")
        #[test]
        fn has_no_bom_and_ends_with_a_newline() {
            let text = render_claude_settings(&["/a"]);
            assert!(text.starts_with('{'));
            assert!(text.ends_with("}\n"));
        }

        /// Rust 侧补充：与 `JSON.stringify(.., null, 2)` 逐字节一致，含空数组与要转义的字符
        /// （期望值由 tsx 跑 virtualdir.ts 取得）
        #[test]
        fn full_text_matches_ts() {
            assert_eq!(
                render_claude_settings(&["/a/b", "D:\\code\\仓库", "q\"t\u{1}\t\u{7f}\u{2028}"]),
                "{\n  \"permissions\": {\n    \"additionalDirectories\": [\n      \"/a/b\",\n      \
                 \"D:\\\\code\\\\仓库\",\n      \"q\\\"t\\u0001\\t\u{7f}\u{2028}\"\n    ]\n  }\n}\n"
            );
            assert_eq!(
                render_claude_settings::<&str>(&[]),
                "{\n  \"permissions\": {\n    \"additionalDirectories\": []\n  }\n}\n"
            );
        }
    }

    /// TS：describe("containerManifestFiles / centralManifestFiles")
    mod manifest_files {
        use super::*;

        /// it("container gets AGENTS.md + CLAUDE.md + .claude/settings.json")
        #[test]
        fn container_gets_three_files() {
            let files = container_manifest_files("p", &["/a"]);
            let rels: Vec<&[&str]> = files.iter().map(|f| f.rel).collect();
            assert_eq!(rels, [&["AGENTS.md"][..], &["CLAUDE.md"], &[".claude", "settings.json"]]);
        }

        /// it("central dir gets no settings.json — members are inside cwd already")
        #[test]
        fn central_dir_gets_no_settings_json() {
            let files = central_manifest_files("p", "b", &[central("x", "/r/x")]);
            let rels: Vec<&[&str]> = files.iter().map(|f| f.rel).collect();
            assert_eq!(rels, [&["AGENTS.md"][..], &["CLAUDE.md"]]);
        }
    }

    /// TS：describe("posixWriteManifestCommand")
    mod posix_write_manifest_command {
        use super::*;

        fn files() -> Vec<ManifestFile> {
            container_manifest_files("p", &["/a"])
        }

        /// it("creates the dir and .claude, then writes each file via printf")
        #[test]
        fn creates_dir_and_claude_then_writes_each_file() {
            let cmd = posix_write_manifest_command("/home/u/.falcon/projects/id", &files());
            assert!(cmd.contains(r#"mkdir -p "$d" "$d"/.claude && "#));
            assert!(cmd.contains(r#"> "$d"/AGENTS.md"#));
            assert!(cmd.contains(r#"> "$d"/CLAUDE.md"#));
            assert!(cmd.contains(r#"> "$d"/.claude/settings.json"#));
        }

        /// it("quotes dir and content so quotes/newlines cannot split the command")
        #[test]
        fn quotes_dir_and_content() {
            let cmd = posix_write_manifest_command("/home/o'brien/.falcon/projects/id", &files());
            assert!(cmd.starts_with(r"d='/home/o'\''brien/.falcon/projects/id'; "));
        }

        /// it("never deletes anything")
        #[test]
        fn never_deletes_anything() {
            let cmd = posix_write_manifest_command("/x", &files());
            assert!(!cmd.contains("rm "));
            assert!(!cmd.contains("rmdir"));
        }

        /// Rust 侧补充：整串与 TS 逐字节一致（tsx 跑 virtualdir.ts 取得）
        #[test]
        fn full_command_matches_ts() {
            let files = vec![
                ManifestFile { rel: &["CLAUDE.md"], content: CLAUDE_MD_BODY.into() },
                ManifestFile { rel: &[".claude", "settings.json"], content: "it's\n".into() },
            ];
            assert_eq!(
                posix_write_manifest_command("/x y", &files),
                "d='/x y'; mkdir -p \"$d\" \"$d\"/.claude && printf %s '@AGENTS.md\n' > \"$d\"/CLAUDE.md && \
                 printf %s 'it'\\''s\n' > \"$d\"/.claude/settings.json"
            );
        }

        /// Rust 侧补充：用 sh 真跑——写出的三个文件与渲染结果逐字节一致（含引号、换行、中文）
        #[cfg(unix)]
        #[test]
        fn runs_in_sh() {
            let tmp = tempfile::tempdir().unwrap();
            let dir = tmp.path().join("o'brien dir").join("projects").join("id");
            let files = container_manifest_files("我的'项目\"", &["/a b/it's", "D:\\仓库\\x"]);
            let status = std::process::Command::new("sh")
                .arg("-c")
                .arg(posix_write_manifest_command(dir.to_str().unwrap(), &files))
                .status()
                .unwrap();
            assert!(status.success());
            for f in &files {
                let path = f.rel.iter().fold(dir.clone(), |p, seg| p.join(seg));
                assert_eq!(std::fs::read_to_string(path).unwrap(), f.content);
            }
        }
    }

    /// TS：describe("windowsWriteManifestCommands")
    mod windows_write_manifest_commands {
        use super::*;

        fn setup() -> (Vec<ManifestFile>, Vec<WindowsManifestWrite>) {
            let files = container_manifest_files("项目", &["D:\\code\\仓库"]);
            let cmds = windows_write_manifest_commands("C:\\Users\\u\\.falcon\\projects\\id", &files);
            (files, cmds)
        }

        /// it("emits one -EncodedCommand per file")
        #[test]
        fn emits_one_encoded_command_per_file() {
            let (files, cmds) = setup();
            assert_eq!(cmds.len(), files.len());
            for WindowsManifestWrite { cmd, .. } in &cmds {
                assert!(cmd.starts_with("powershell -NoProfile -NonInteractive -EncodedCommand "));
            }
        }

        /// it("mkdirs the parent then WriteAllBytes from stdin base64")
        #[test]
        fn mkdirs_the_parent_then_write_all_bytes() {
            let (_, cmds) = setup();
            let script = decode(&cmds[2].cmd);
            assert_match(&script, r"New-Item -ItemType Directory -Force -Path ");
            assert_match(&script, r"\[Convert\]::FromBase64String\(\[Console\]::In\.ReadToEnd\(\)\)");
            assert!(
                script.contains(r"[IO.File]::WriteAllBytes('C:\Users\u\.falcon\projects\id\.claude\settings.json', $b)")
            );
        }

        /// it("stdin carries the exact UTF-8 bytes — CJK survives the trip")
        #[test]
        fn stdin_carries_the_exact_utf8_bytes() {
            let (files, cmds) = setup();
            for (i, WindowsManifestWrite { stdin_base64, .. }) in cmds.iter().enumerate() {
                let bytes = base64::engine::general_purpose::STANDARD.decode(stdin_base64).unwrap();
                assert_eq!(String::from_utf8(bytes).unwrap(), files[i].content);
            }
        }

        /// Rust 侧补充：单段文件的 parent 就是 dir 原样（不经 joinPath 归一），两段的才拼
        #[test]
        fn parent_of_top_level_file_is_dir_verbatim() {
            let (_, cmds) = setup();
            assert!(decode(&cmds[0].cmd).contains(r"-Force -Path 'C:\Users\u\.falcon\projects\id' | Out-Null"));
            assert!(decode(&cmds[2].cmd).contains(r"-Force -Path 'C:\Users\u\.falcon\projects\id\.claude' | Out-Null"));
            let cmds = windows_write_manifest_commands("C:/x/", &container_manifest_files("p", &["/a"]));
            assert!(decode(&cmds[0].cmd).contains("-Force -Path 'C:/x/' | Out-Null"));
            assert!(decode(&cmds[0].cmd).contains(r"WriteAllBytes('C:\x\AGENTS.md', $b)"));
        }
    }

    /// TS：describe("posixRemoveVirtualDirCommand")
    mod posix_remove_virtual_dir_command {
        use super::*;

        fn cmd() -> String {
            posix_remove_virtual_dir_command("/home/u/.falcon/projects/id")
        }

        /// it("removes only the three fixed files, then rmdirs non-recursively")
        #[test]
        fn removes_only_the_three_fixed_files() {
            let cmd = cmd();
            assert!(cmd.contains(r#"rm -f -- "$d"/AGENTS.md "$d"/CLAUDE.md "$d"/.claude/settings.json; "#));
            assert!(cmd.contains(r#"rmdir -- "$d"/.claude"#));
            assert!(!cmd.contains("rm -r"));
        }

        /// it("reports gone|left on stdout, and gone when the dir never existed")
        #[test]
        fn reports_gone_or_left() {
            let cmd = cmd();
            assert!(cmd.contains(r#"if [ ! -e "$d" ]; then printf gone; "#));
            assert!(cmd.contains("then printf gone; else printf left; fi"));
        }

        /// Rust 侧补充：用 sh 真跑——只剩清单时 gone，有别的文件时 left 且别的文件还在，目录不在时 gone
        #[cfg(unix)]
        #[test]
        fn runs_in_sh() {
            let run = |dir: &std::path::Path| {
                let out = std::process::Command::new("sh")
                    .arg("-c")
                    .arg(posix_remove_virtual_dir_command(dir.to_str().unwrap()))
                    .output()
                    .unwrap();
                assert!(out.status.success());
                String::from_utf8(out.stdout).unwrap()
            };
            let write_all = |dir: &std::path::Path| {
                for f in container_manifest_files("p", &["/a"]) {
                    let path = f.rel.iter().fold(dir.to_path_buf(), |p, seg| p.join(seg));
                    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
                    std::fs::write(path, f.content).unwrap();
                }
            };
            let tmp = tempfile::tempdir().unwrap();
            let dir = tmp.path().join("it's");
            write_all(&dir);
            assert_eq!(run(&dir), "gone");
            assert!(!dir.exists());
            assert_eq!(run(&dir), "gone");
            write_all(&dir);
            std::fs::write(dir.join("notes.txt"), "x").unwrap();
            assert_eq!(run(&dir), "left");
            assert!(dir.join("notes.txt").exists());
            assert!(!dir.join("AGENTS.md").exists() && !dir.join(".claude").exists());
        }
    }

    /// TS：describe("windowsRemoveVirtualDirCommand")
    mod windows_remove_virtual_dir_command {
        use super::*;

        fn script() -> String {
            decode(&windows_remove_virtual_dir_command("C:\\u\\.falcon\\projects\\a[1]b"))
        }

        /// it("uses literal-path IO.File/IO.Directory deletes, never Remove-Item or -Recurse")
        #[test]
        fn uses_literal_path_deletes() {
            let script = script();
            assert_match(&script, r"\[IO\.File\]::Delete\(\(Join-Path \$d 'AGENTS\.md'\)\)");
            assert_match(&script, r"\[IO\.File\]::Delete\(\(Join-Path \$d 'CLAUDE\.md'\)\)");
            assert_match(&script, r"\[IO\.File\]::Delete\(\(Join-Path \$d '\.claude\\settings\.json'\)\)");
            assert_match(&script, r"\[IO\.Directory\]::Delete\(\(Join-Path \$d '\.claude'\), \$false\)");
            assert_match(&script, r"\[IO\.Directory\]::Delete\(\$d, \$false\); 'gone'");
            assert!(!script.contains("Remove-Item"));
            assert!(!script.contains("-Recurse"));
        }

        /// it("short-circuits to gone when the dir does not exist")
        #[test]
        fn short_circuits_to_gone() {
            assert_match(&script(), r"if \(-not \(Test-Path -LiteralPath \$d\)\) \{ 'gone'; exit 0 \}");
        }
    }

    /// TS：describe("centralManifestSweepCommand")
    mod central_manifest_sweep_command {
        use super::*;

        /// it("posix: deletes AGENTS.md only when marked, CLAUDE.md only on exact match")
        #[test]
        fn posix_guards() {
            let cmd = central_manifest_sweep_command(Posix, "/repos/multi-feat");
            assert!(cmd.contains(r#"head -n 1 "$d"/AGENTS.md | grep -qF 'generated by falcon'"#));
            assert!(cmd.contains(r#"[ "$(cat "$d"/CLAUDE.md)" = '@AGENTS.md' ]"#));
            assert!(!cmd.contains("rm -r"));
            // 只碰这两个 basename
            assert_eq!(cmd.matches("rm -f").count(), 2);
        }

        /// it("windows: same guards via Get-Content, deletes via IO.File only")
        #[test]
        fn windows_guards() {
            let script = decode(&central_manifest_sweep_command(Windows, "C:\\repos\\multi-feat"));
            assert_match(&script, r"Get-Content -LiteralPath \$a -First 1\) -like '\*generated by falcon\*'");
            assert_match(&script, r"Get-Content -LiteralPath \$c -Raw\)\.Trim\(\) -eq '@AGENTS\.md'");
            assert!(!script.contains("Remove-Item"));
            assert!(!script.contains("-Recurse"));
        }

        /// it("quotes a central dir containing single quotes")
        #[test]
        fn quotes_a_central_dir_with_single_quotes() {
            let cmd = central_manifest_sweep_command(Posix, "/home/o'brien/multi-x");
            assert!(cmd.starts_with(r"d='/home/o'\''brien/multi-x'; "));
        }
    }
}
