/**
 * 虚拟项目目录与结构清单：让 Claude Code 等 coding agent 知道并能访问
 * 多仓库项目的全部成员仓库。
 *
 * 两个落点：
 * - 容器（multi != null 且非派生行）没有聚合目录，在 <falcon 根>/projects/<projectId>/
 *   生成一个虚拟目录当会话 cwd：AGENTS.md（成员绝对路径清单）+ CLAUDE.md（@import）
 *   + .claude/settings.json（Claude Code 的越 cwd 目录授权）。
 * - 批量派生的集中目录本身已经聚合了全部 worktree，只补 AGENTS.md + CLAUDE.md。
 *
 * 刻意不用软链聚合：实测 Claude Code 的 Glob 与 ripgrep 默认都不跟随软链目录，
 * 从聚合根递归搜索一无所获；带沙箱的 agent 还可能按 realpath 拒绝出逃。
 * 清单 + 真实路径对所有 agent 都是渐进增强（不认 settings.json 的最多退化成逐次授权）。
 *
 * 目录名用 projectId 不用 nameSlug：重名不撞、改名零孤儿，路径 = f(root, id)
 * 确定性可算，不用加 DB 列。内容全部模板确定性渲染——覆盖写天然幂等，
 * 守护删除（remove.ts）才能按字面比对"这是不是我们写的文件"。
 *
 * 与 paste.ts 同一分层：纯函数（路径/渲染/脚本构造）+ 本地 node:fs 例外。
 * SSH 侧不走 SFTP（理由同 fs.ts）；Windows 远端内容走 stdin base64 +
 * WriteAllBytes——Set-Content 默认按 ANSI 代码页写（中文机器上变 GBK），
 * `-Encoding UTF8` 又带 BOM（settings.json 的 JSON 解析会被它弄坏），
 * 内容内联进 -EncodedCommand 还可能顶穿 cmd.exe 的 8191 字符上限，全都不能用。
 */
import fs from "node:fs";
import path from "node:path";
import { joinPath } from "./git/path.js";
import { encodePowerShell, quotePosix, quotePowerShell, type HostKind } from "./zellij/host.js";

/**
 * 生成物标记，放 AGENTS.md 首行注释里。守护删除按"首行含此标记"判断文件
 * 还是不是我们写的——刻意用 ASCII：跨编码可 grep，远端 head/grep 不吃编码亏。
 */
export const FALCON_GENERATED_MARK = "generated by falcon";

/**
 * CLAUDE.md 的确定性全文：单行 @import 指向 AGENTS.md。
 * 不复制全文——Claude Code 会同时认两个文件，复制会加载出双份内容；
 * 守护删除按"全文 trim 后精确等于 @AGENTS.md"比对，改一个字都视为用户文件。
 */
export const CLAUDE_MD_BODY = "@AGENTS.md\n";

/** 清单文件：rel 用分段数组（写入/删除两侧共用一处真相，不手拼分隔符） */
export interface ManifestFile {
  rel: string[];
  content: string;
}

/** 容器虚拟目录的固定文件清单——删除侧只认这三个名字，多一个都不碰 */
const VIRTUAL_DIR_FILES: readonly (readonly string[])[] = [
  ["AGENTS.md"],
  ["CLAUDE.md"],
  [".claude", "settings.json"],
];

/** 虚拟目录：<falcon 根>/projects/<projectId>。root = 本地 dataDir 或远端 ~/.falcon */
export function virtualProjectDir(kind: HostKind, root: string, projectId: string): string {
  return joinPath(kind, root, "projects", projectId);
}

// ---------------- 渲染 ----------------

/**
 * 容器版 AGENTS.md。措辞是给 agent 看的操作指引，三条告诫对应实测到的坑：
 * 递归搜索不跟软链同理也搜不到 cwd 外——必须逐成员为根；成员是独立仓库。
 */
export function renderContainerAgentsMd(projectName: string, memberDirs: string[]): string {
  const members = memberDirs.map((d) => `- ${d}`).join("\n");
  return `<!-- ${FALCON_GENERATED_MARK} -->
<!-- 本文件与同目录的 CLAUDE.md、.claude/settings.json 由 falcon 自动生成并维护，
     成员变更或重开会话时会被整体覆盖，请勿手工编辑。 -->

# ${projectName}（多仓库项目）

这是 falcon 为多仓库项目生成的虚拟项目目录：**当前目录下没有代码**，
全部代码都在下面列出的成员仓库里。在本项目中工作时请注意：

- 递归搜索（grep / glob / 代码索引）必须以每个成员目录为根分别进行，
  以当前目录为根搜索将一无所获。
- 读写文件一律使用成员目录下的绝对路径。
- 各成员是相互独立的 git 仓库，提交、分支操作要逐个成员进行，
  不要假设它们共享同一个仓库。

## 成员仓库

${members}
`;
}

/** 集中目录版：成员都在 cwd 内，用相对路径；不需要"cwd 下没有代码"的告诫 */
export function renderCentralAgentsMd(
  projectName: string,
  branch: string,
  members: { base: string; repoDir: string }[]
): string {
  const list = members.map((m) => `- ./${m.base}/（源仓库 ${m.repoDir}）`).join("\n");
  return `<!-- ${FALCON_GENERATED_MARK} -->
<!-- 本文件由 falcon 在批量派生时生成，删除该派生项目时会被一并清理。 -->

# ${projectName}（多仓库批量派生，分支 ${branch}）

当前目录是 falcon 批量派生出的集中目录，下列子目录各是一个成员仓库的
git worktree（统一检出分支 ${branch}）。各成员是相互独立的仓库，
提交、分支操作要逐个成员进行。

## 成员

${list}
`;
}

/** Claude Code 的越 cwd 目录授权。JSON.stringify 自带反斜杠转义，无 BOM、带尾换行 */
export function renderClaudeSettings(memberDirs: string[]): string {
  return `${JSON.stringify({ permissions: { additionalDirectories: memberDirs } }, null, 2)}\n`;
}

/** 容器虚拟目录的三个文件 */
export function containerManifestFiles(projectName: string, memberDirs: string[]): ManifestFile[] {
  return [
    { rel: ["AGENTS.md"], content: renderContainerAgentsMd(projectName, memberDirs) },
    { rel: ["CLAUDE.md"], content: CLAUDE_MD_BODY },
    { rel: [".claude", "settings.json"], content: renderClaudeSettings(memberDirs) },
  ];
}

/** 集中目录的两个文件——成员都在 cwd 内，settings.json 没有存在的理由 */
export function centralManifestFiles(
  projectName: string,
  branch: string,
  members: { base: string; repoDir: string }[]
): ManifestFile[] {
  return [
    { rel: ["AGENTS.md"], content: renderCentralAgentsMd(projectName, branch, members) },
    { rel: ["CLAUDE.md"], content: CLAUDE_MD_BODY },
  ];
}

// ---------------- 写入 ----------------

/**
 * POSIX：一条命令建目录 + 逐文件 printf 覆盖写（ensureDirsScript 同款）。
 * 内容经 quotePosix 内联，单引号里的换行由 sh 原样保留；rel 段是我们自己的
 * 固定 ASCII 文件名，不需要引号。退出码 = 链上第一个失败者，调用方查 res.code。
 */
export function posixWriteManifestCommand(dir: string, files: ManifestFile[]): string {
  const subdirs = [...new Set(files.filter((f) => f.rel.length > 1).map((f) => f.rel.slice(0, -1).join("/")))];
  const mkTargets = [`"$d"`, ...subdirs.map((s) => `"$d"/${s}`)].join(" ");
  const writes = files.map((f) => `printf %s ${quotePosix(f.content)} > "$d"/${f.rel.join("/")}`);
  return `d=${quotePosix(dir)}; mkdir -p ${mkTargets} && ${writes.join(" && ")}`;
}

/**
 * Windows 远端：逐文件一条 -EncodedCommand，配 SshLink.execWithInput 喂 base64。
 * 编码取舍见文件头注释。New-Item -Force 对已存在目录是幂等的（mkdirPS 同款，
 * 创建路径可以用 -Path，通配陷阱只在删除侧——见 install.ts 的 cleanup 注释）。
 */
export function windowsWriteManifestCommands(
  dir: string,
  files: ManifestFile[]
): { cmd: string; stdinBase64: string }[] {
  return files.map((f) => {
    const target = joinPath("windows", dir, ...f.rel);
    const parent = f.rel.length > 1 ? joinPath("windows", dir, ...f.rel.slice(0, -1)) : dir;
    const script = [
      `New-Item -ItemType Directory -Force -Path ${quotePowerShell(parent)} | Out-Null`,
      `$b = [Convert]::FromBase64String([Console]::In.ReadToEnd())`,
      `[IO.File]::WriteAllBytes(${quotePowerShell(target)}, $b)`,
    ].join("; ");
    return { cmd: encodePowerShell(script), stdinBase64: Buffer.from(f.content, "utf8").toString("base64") };
  });
}

/** 本地（含 Windows 本地——node:fs 不吃 cmd 8191 与代码页的亏）：直接覆盖写 */
export async function writeLocalManifest(dir: string, files: ManifestFile[]): Promise<void> {
  for (const f of files) {
    const target = path.join(dir, ...f.rel);
    await fs.promises.mkdir(path.dirname(target), { recursive: true });
    await fs.promises.writeFile(target, f.content, "utf8");
  }
}

// ---------------- 容器虚拟目录清理 ----------------
// 虚拟目录住在 falcon 根下，属 falcon 自有目录，参照 paste.ts 自行清理，
// 不进 remove.ts（那里管的是用户可见路径）。但删除动作同样克制：只删固定
// 文件名 + 非递归 rmdir——虚拟目录是会话 cwd，agent/用户可能在里面落了
// 别的文件，非空就整目录保留，stdout 报 left 让上层给 warning。

/** stdout 协议：gone = 目录已不在；left = 目录还在（内有其他文件） */
export function posixRemoveVirtualDirCommand(dir: string): string {
  const files = VIRTUAL_DIR_FILES.map((rel) => `"$d"/${rel.join("/")}`).join(" ");
  return (
    `d=${quotePosix(dir)}; rm -f -- ${files}; ` +
    `rmdir -- "$d"/.claude 2>/dev/null; ` +
    `if [ ! -e "$d" ]; then printf gone; ` +
    `elif rmdir -- "$d" 2>/dev/null; then printf gone; else printf left; fi`
  );
}

/**
 * Windows：[IO.File]::Delete / [IO.Directory]::Delete($p, $false) 吃字面量且
 * 非递归——不用 Remove-Item（-Path 的通配陷阱见 install.ts 的 cleanup 注释）。
 * File.Delete 对不存在的文件不抛，但父目录不存在时抛 DirectoryNotFound，
 * 所以每条都包 try/catch：删不掉的后果只是 rmdir 失败 → left，方向安全。
 */
export function windowsRemoveVirtualDirCommand(dir: string): string {
  const deletes = VIRTUAL_DIR_FILES.map(
    (rel) => `try { [IO.File]::Delete((Join-Path $d ${quotePowerShell(rel.join("\\"))})) } catch {}`
  );
  const script = [
    `$d = ${quotePowerShell(dir)}`,
    `if (-not (Test-Path -LiteralPath $d)) { 'gone'; exit 0 }`,
    ...deletes,
    `try { [IO.Directory]::Delete((Join-Path $d '.claude'), $false) } catch {}`,
    `try { [IO.Directory]::Delete($d, $false); 'gone' } catch { 'left' }`,
  ].join("; ");
  return encodePowerShell(script);
}

export function removeVirtualDirCommand(kind: HostKind, dir: string): string {
  return kind === "windows" ? windowsRemoveVirtualDirCommand(dir) : posixRemoveVirtualDirCommand(dir);
}

/** 本地清理。ENOENT 一律视为已删干净；其他失败（如权限）落 left，上层给 warning */
export function removeLocalVirtualDir(dir: string): "gone" | "left" {
  for (const rel of VIRTUAL_DIR_FILES) {
    try {
      fs.unlinkSync(path.join(dir, ...rel));
    } catch {
      // ENOENT = 本来就没有；其他错误留给下面的 rmdir 去失败
    }
  }
  try {
    fs.rmdirSync(path.join(dir, ".claude"));
  } catch {
    // 不存在或非空都不要紧，只影响最外层 rmdir 的结果
  }
  try {
    fs.rmdirSync(dir);
  } catch (err) {
    return (err as NodeJS.ErrnoException).code === "ENOENT" ? "gone" : "left";
  }
  return "gone";
}

// ---------------- 集中目录清单的守护删除脚本 ----------------
// 只构造脚本；执行住在 git/remove.ts（全仓库唯一删用户可见路径的地方）。
// 守护条件与生成物一一对应：AGENTS.md 首行含标记、CLAUDE.md 全文 trim 后
// 精确等于 @AGENTS.md——用户改写过的内容视为用户文件，宁可不删（后续的
// rmdir 会因非空失败，既有 warning 带路径，方向安全）。

export function posixCentralManifestSweepCommand(central: string): string {
  return (
    `d=${quotePosix(central)}; ` +
    `if [ -f "$d"/AGENTS.md ] && head -n 1 "$d"/AGENTS.md | grep -qF ${quotePosix(FALCON_GENERATED_MARK)}; ` +
    `then rm -f -- "$d"/AGENTS.md; fi; ` +
    `if [ -f "$d"/CLAUDE.md ] && [ "$(cat "$d"/CLAUDE.md)" = ${quotePosix(CLAUDE_MD_BODY.trim())} ]; ` +
    `then rm -f -- "$d"/CLAUDE.md; fi`
  );
}

export function windowsCentralManifestSweepCommand(central: string): string {
  const script = [
    `$d = ${quotePowerShell(central)}`,
    `$a = Join-Path $d 'AGENTS.md'`,
    `if ((Test-Path -LiteralPath $a) -and ` +
      `((Get-Content -LiteralPath $a -First 1) -like ${quotePowerShell(`*${FALCON_GENERATED_MARK}*`)})) ` +
      `{ [IO.File]::Delete($a) }`,
    `$c = Join-Path $d 'CLAUDE.md'`,
    `if ((Test-Path -LiteralPath $c) -and ` +
      `((Get-Content -LiteralPath $c -Raw).Trim() -eq ${quotePowerShell(CLAUDE_MD_BODY.trim())})) ` +
      `{ [IO.File]::Delete($c) }`,
  ].join("; ");
  return encodePowerShell(script);
}

export function centralManifestSweepCommand(kind: HostKind, central: string): string {
  return kind === "windows"
    ? windowsCentralManifestSweepCommand(central)
    : posixCentralManifestSweepCommand(central);
}
